EBContactManagement/Models/ContactType.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBContactManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContactType()
        {
            this.ContactMades = new HashSet<ContactMade>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactMade> ContactMades { get; set; }
    }
}

EBContactManagement/Models/HouseHold.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.UI.WebControls;

namespace EBContactManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HouseHold
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HouseHold()
        {
            this.People = new HashSet<Person>();
            this.ContactMades = new HashSet<ContactMade>();
            this.BusinessMeetingAttendeds = new HashSet<BusinessMeetingAttended>();
            this.WorkDayAttendeds = new HashSet<WorkDayAttended>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Priority { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public Nullable<System.DateTime> ProspectDate { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public Nullable<System.DateTime> InitialContact { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public Nullable<System.DateTime> AssociateDate { get; set; }
        public string AssociateGuide { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public Nullable<System.DateTime> ForumDate { get; set; }
        public string MetWith { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public Nullable<System.DateTime> MemberDate { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public Nullable<System.DateTime> MoveInDate { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public Nullable<System.DateTime> LastContact { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public Nullable<System.DateTime> NextContact { get; set; }
        public string Notes { get; set; }
        [DisplayName("How heard about EB")]
        public string HowHeard { get; set; }

        public bool Deleted { get; set; }

        public virtual Status Status1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person> People { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactMade> ContactMades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BusinessMeetingAttended> BusinessMeetingAttendeds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkDayAttended> WorkDayAttendeds { get; set; }
    }
}

EBContactManagement/Models/Person.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace EBContactManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.PersonPhones = new HashSet<PersonPhone>();
        }
    
        public int ID { get; set; }
        public Nullable<int> HouseHoldID { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string State { get; set; }

        [RegularExpression(@"^\d{5}(-\d{4})?$",ErrorMessage = "Invalid zip code")]
        public string Zip { get; set; }

        [DataType(DataType.EmailAddress, ErrorMessage = "Invalid Email Address")]
        public string Email { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
    
        public virtual HouseHold HouseHold { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonPhone> PersonPhones { get; set; }
    }
}

EBContactManagement/Models/WorkDayAttended.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace EBContactManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkDayAttended
    {
        public int ID { get; set; }
        public Nullable<int> HouseHoldId { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public Nullable<System.DateTime> AttendedDate { get; set; }
    
        public virtual HouseHold HouseHold { get; set; }
    }
}

EBContactManagement/Controllers/HouseHoldsController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using CsvHelper;
using EBContactManagement.Models;
using EBContactManagement.Models.Service;
using EBContactManagement.Models.ViewModel;
using log4net;
using MiraComp.MVC;
using MiraComp.MVC.FilterAttribute;
using Newtonsoft.Json;

namespace EBContactManagement.Controllers
{
    [LogException]
    public class HouseHoldsController : Controller
    {
        private EBContactEntities db = new EBContactEntities();
        private HouseholdService _householdService = new HouseholdService();
        protected readonly ILog _logger = LogManager.GetLogger(typeof(HouseHoldsController));

        public HouseHoldsController()
        {
            _logger.Debug("ctor start");
            db.Database.Log = (dbLog => _logger.Info(dbLog));
            _logger.Debug("ctor finish");
        }

        public ActionResult IndexOld()
        {
            _logger.Debug("Index start");
            ViewBag.StatusList = GetStatuslist();
            var list = _householdService.getHouseHolds();
            _logger.Debug("Index finish");
            return View("Index",list);
        }


        public ActionResult Index()
        {
            _logger.Debug("IndexPlus start");
            var userAgent = Request.UserAgent;
            _logger.Info("(admin)User agent: " + userAgent);
            ViewBag.StatusList = GetStatuslist();
            var list = new List<HouseholdListView>();
            _logger.Debug("IndexPlus finish");
            return View("IndexPlus",list);
        }


        private  List<SelectListItem> GetStatuslist()
        {
            var list = _householdService.GetStatusList();

            var selectlist = list.Select(item => new SelectListItem { Text = item.Status1, Value = item.ID.ToString() }).ToList();

            selectlist.Insert(0,new SelectListItem{Text = "--Choose--",Value = "0"});

            return selectlist;
        }

        // GET: HouseHolds/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HouseHold houseHold = db.HouseHolds.Find(id);
            if (houseHold == null)
            {
                return HttpNotFound();
            }
            return View(houseHold);
        }

        // GET: HouseHolds/Create
        public ActionResult Create()
        {
            createSelectLists();
            var houseHold = new HouseHold();
            houseHold.People.Add(new Person());
            db.HouseHolds.Add(houseHold);

            db.SaveChanges();

            return RedirectToAction("Edit", new {id = houseHold.ID});
        }

        // POST: HouseHolds/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "ID,Status,Priority,ProspectDate,InitialContact,AssociateDate,AssociateGuide,ForumDate,MetWith,MemberDate,MoveInDate,LastContact,NextContact,Notes")] HouseHold houseHold)
        public ActionResult Create( HouseHold houseHold)
        {
            if (ModelState.IsValid)
            {
                db.HouseHolds.Add(houseHold);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            createSelectLists();
            return View(houseHold);
        }

        // GET: HouseHolds/Edit/5
        public ActionResult Edit(int? id)
        {
            _logger.Debug("Edit get start");
            ViewBag.ErrorMessage = string.Empty;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HouseHold houseHold = db.HouseHolds.Find(id);
            if (houseHold == null)
            {
                return HttpNotFound();
            }

            createSelectLists();
            _logger.Debug("Edit get end");
            return View(houseHold);
        }

        private void createSelectLists()
        {
            var contacters = db.Contacters.Where(x => x.Active.HasValue && x.Active.Value).OrderBy(x => x.Priority);
            ViewBag.StatusList = new SelectList(db.Status, "ID", "Status1");
            ViewBag.PhoneType = new SelectList(db.PhoneTypes, "ID", "Description");
            ViewBag.Contacter = new SelectList(contacters, "ID", "Name");
            ViewBag.ContactTypes = new SelectList(db.ContactTypes, "ID", "Name");
        }

        // POST: HouseHolds/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "ID,Status,Priority,ProspectDate,InitialContact,AssociateDate,AssociateGuide,ForumDate,MetWith,MemberDate,MoveInDate,LastContact,NextContact,Notes")] HouseHold houseHold)
        public ActionResult Edit(HouseHold houseHold)
        {
            ViewBag.ErrorMessage = string.Empty;
            var houseHoldFromDB = db.HouseHolds.Find(houseHold.ID);
            _householdService.updateModel(houseHoldFromDB, houseHold);

            if (ModelState.IsValid)
            {
                db.SaveChanges();
                ViewBag.ErrorMessage = "Changes saved " + DateTime.Now.ToLongTimeString();
            }
            createSelectLists();
            return View(houseHold);
        }

        [HttpPost]
        public ActionResult AddContact(int id)
        {
            var houseHold = db.HouseHolds.Find(id);
            var contact = new ContactMade {ContactDate = DateTime.Today};
            houseHold.ContactMades.Add(contact);
            db.SaveChanges();
           
            createSelectLists();
            var partialView = PartialView("_contact", contact).RenderToString();
            return Json(new { success = true, html = partialView }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult RemoveContact(int id,int cid)
        {
            var houseHold = db.HouseHolds.Find(id);
            var contact = houseHold.ContactMades.Single(x => x.ID == cid);
            houseHold.ContactMades.Remove(contact);
            db.SaveChanges();

            return Json(new { success = true }, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public ActionResult AddPerson(int id)
        {
            var houseHold = db.HouseHolds.Find(id);
            var contact = new Person();
            houseHold.People.Add(contact);
            db.SaveChanges();

            createSelectLists();
            var partialView = PartialView("_person", contact).RenderToString();
            return Json(new { success = true, html = partialView }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult RemovePerson(int id, int pid)
        {
            var houseHold = db.HouseHolds.Find(id);
            var person = houseHold.People.Single(x => x.ID == pid);
            houseHold.People.Remove(person);
            db.SaveChanges();

            return Json(new { success = true }, JsonRequestBehavior.AllowGet);
        }



        [HttpPost]
        public ActionResult AddBusinessMeeting(int id)
        {
            var houseHold = db.HouseHolds.Find(id);
            var meeting = new BusinessMeetingAttended();
            houseHold.BusinessMeetingAttendeds.Add(meeting);
            db.SaveChanges();

            createSelectLists();
            var partialView = PartialView("_BusinessMeeting", meeting).RenderToString();
            return Json(new { success = true, html = partialView }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult RemoveBusinessMeeting(int id, int pid)
        {
            var houseHold = db.HouseHolds.Find(id);
            var meeting = houseHold.BusinessMeetingAttendeds.Single(x => x.ID == pid);
            houseHold.BusinessMeetingAttendeds.Remove(meeting);
            db.SaveChanges();

            return Json(new { success = true }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult AddWorkday(int id)
        {
            var houseHold = db.HouseHolds.Find(id);
            var workday = new WorkDayAttended();
            houseHold.WorkDayAttendeds.Add(workday);
            db.SaveChanges();

            createSelectLists();
            var partialView = PartialView("_WorkDayAttended", workday).RenderToString();
            return Json(new { success = true, html = partialView }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult RemoveWorkday(int id, int pid)
        {
            var houseHold = db.HouseHolds.Find(id);
            var workday = houseHold.WorkDayAttendeds.Single(x => x.ID == pid);
            houseHold.WorkDayAttendeds.Remove(workday);
            db.SaveChanges();

            return Json(new { success = true }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult AddPhone(int id,int pid, string containerPrefix)
        {
            var houseHold = db.HouseHolds.Find(id);
            var person = houseHold.People.Single(m => m.ID == pid);
            var phone = new PersonPhone();
            person.PersonPhones.Add(phone);
            db.SaveChanges();

            createSelectLists();
            ViewData.TemplateInfo.HtmlFieldPrefix = containerPrefix;
            var partialView = PartialView("_phone", phone).RenderToString();
            return Json(new { success = true, html = partialView }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]

EBContactManagement/Views/HouseHolds/Delete.cshtml
@model EBContactManagement.Models.HouseHold

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>HouseHold</h4>
    <hr />
    <dl class="dl-horizontal">
            @foreach (var p in Model.People)
            {
                <dt>
                    Person
                </dt>
                <dd>
                    @p.LastName
                    &nbsp;
                    @p.FirstName
                </dd>
            }

        <dt>
            @Html.DisplayNameFor(model => model.Priority)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Priority)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProspectDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProspectDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InitialContact)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InitialContact)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AssociateDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AssociateDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AssociateGuide)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AssociateGuide)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ForumDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ForumDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MetWith)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MetWith)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MemberDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MemberDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MoveInDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MoveInDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastContact)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastContact)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NextContact)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NextContact)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Notes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Notes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status1.Status1)
        </dt>

            <dd>
                @if (Model.Status != null)
                {
                    @Html.DisplayFor(model => model.Status1.Status1)
                }
            </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

EBContactManagement/Views/HouseHolds/Index.cshtml
@model List<EBContactManagement.Models.ViewModel.HouseholdListView>

@{ ViewBag.Title = "Index";
                Layout = "~/Views/Shared/_Layout.cshtml"; }

@section css {
    <link href="~/Content/jquery.bootgrid.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
}


<div class="row">
    <div class="col-xs-2">
        @Html.ActionLink("Create Prospect", "Create", null, new { @class = "btn btn-primary" })
    </div>
    <div class="col-xs-10 text-right">
        <input id="btnMultisort" type="submit" value="Multi Column Sort" class="btn btn-outline-secondary btn-sm" />
        <input id="btnDown" type="submit" value="Export selected" class="btn btn-outline-secondary btn-sm" />
    </div>
    @*<div id="col-xs-6 clearfix">

            <div id="accordian">
                <div class="card">
                    <div class="card-header">
                        <a class="card-link" data-toggle="collapse" href="#collapseOne">
                            Filter
                        </a>
                    </div>
                    <div id="collapseOne" class="collapse" data-parent="#accordion">
                        <div class="card-body">
                            @Html.ListBox("StatusList", (IEnumerable<SelectListItem>) ViewBag.StatusList, new {id = "statuslist"})
                            <br/>
                            @Html.TextBox("StartDate", "", new {@type = "Date", @id = "txtStartDate"})
                            <br/>
                            @Html.TextBox("EndDate", "", new {@type = "Date", @id = "txtEndDate"})
                            <br/>
                            <input id="btnFilter" type="submit" value="Filter" class="btn btn-outline-secondary btn-sm"/>
                        </div>
                    </div>
                </div>
            </div>
        </div>*@

</div>


<div class="text-danger">
    <span id="spnError"></span>
</div>

<table id="tblProspects" class="table table-condensed table-hover table-striped" data-toggle="bootgrid88">
    <thead>
        <tr>
            <th data-column-id="name">
                Name
            </th>
            <th data-column-id="status">
                Status
            </th>
            <th data-column-id="id" data-type="numeric" data-order="desc" data-visible="true" data-width="5em" data-identifier="true">
                ID
            </th>
            <th data-column-id="lastcontact">
                Last Contact
            </th>
            <th data-column-id="link" data-formatter="link" data-sortable="false">Commands</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Name)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Status)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.ID)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.LastContact, "Date")
    </td>
    <td>

        @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
        @Html.ActionLink("Delete", "Delete", new { id = item.ID })
    </td>
</tr>}
    </tbody>
</table>

<script type="text/javascript">
    var exportUrl = '@Url.Action("ExportSelected", "HouseHolds")';
    var downloadUrl = '@Url.Action("DownloadSelected", "HouseHolds")';
</script>


@section Scripts {
    <script src="~/Scripts/jquery.bootgrid.min.js"></script>
    <script src="~/Scripts/jquery.bootgrid.fa.min.js"></script>
    <script src="~/Scripts/app/index5.js"></script>
}

EBContactManagement/Views/HouseHolds/IndexPlus.cshtml
@model List<EBContactManagement.Models.ViewModel.HouseholdListView>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section css {
    <link href="~/Content/jquery.bootgrid.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
}

<noscript>
    <p style="color: red">
        This site does not work with javascript disabled. Instructions to enable javascript
        can be found <a href="http://activatejavascript.org" target="_blank">here</a>
    </p>
</noscript>

<div class="row">
    <div class="col-sm-4">
        @Html.ActionLink("Create Prospect", "Create", null, new { @class = "btn btn-primary" })
    </div>


    <div class="col-sm-2">
        <input id="btnMultisort" type="submit" value="Multi Column Sort" class="btn btn-outline-secondary btn-sm"/>
    </div>
    <div class="col-sm-2">
        <input id="btnDown" type="submit" value="Export selected" class="btn btn-outline-secondary btn-sm"/>
    </div>
    <div class="col-sm-4">
        <button class="btn btn-outline-secondary btn-sm" type="button" data-toggle="collapse" data-target="#filterDiv" aria-expanded="false" aria-controls="collapseExample">
            Show filter
        </button>
    </div>
</div>
<div class="row">

    <div id="filterDiv" class="collapse col-sm-4 col-sm-offset-8" >
        <div class="card card-body">
            @Html.Label("Status(es)")
            <br/>
            @Html.ListBox("StatusList", (IEnumerable<SelectListItem>) ViewBag.StatusList, new {id = "statuslist"})
            <br/>
            @Html.Label("Start Date:")
            @Html.TextBox("StartDate", "", new {@type = "Date", @id = "txtStartDate"})
            <br/>
            @Html.Label("End Date:")
            @Html.TextBox("EndDate", "", new {@type = "Date", @id = "txtEndDate"})
            <br/>
            <input id="btnFilter" type="submit" value="Apply Filter" class="btn btn-primary btn-sm"/>
        </div>
    </div>

</div>


<div class="text-danger">
    <span id="spnError"></span>
</div>

<table id="tblProspects" class="table table-condensed table-hover table-striped" data-toggle="bootgrid88">
    <thead>
        <tr>
            <th data-column-id="Name">
                Name
            </th>
            <th data-column-id="Status">
                Status
            </th>
            <th data-column-id="ID" data-type="numeric" data-order="desc" data-visible="true" data-width="5em" data-identifier="true">
                ID
            </th>
            <th data-column-id="LastContact" data-converter="date">
                Last Contact
            </th>
            <th data-column-id="link" data-formatter="link" data-sortable="false">Commands</th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>

<script type="text/javascript">
    var exportUrl = '@Url.Action("ExportSelected", "HouseHolds")';
    var downloadUrl = '@Url.Action("DownloadSelected", "HouseHolds")';
    var fetchUrl = '@Url.Action("Fetch","Households")';
</script>


@section Scripts {
    <script src="~/Scripts/jquery.bootgrid.min.js"></script>
    <script src="~/Scripts/jquery.bootgrid.fa.min.js"></script>
    <script src="~/Scripts/moment.min.js"></script>
    <script src="~/Scripts/app/indexPlus.js"></script>
}

EBContactManagement/Views/HouseHolds/_BusinessMeeting.cshtml
@model EBContactManagement.Models.BusinessMeetingAttended

<li>
    @using (Html.BeginCollectionItem("BusinessMeetingAttendeds"))
    {
        <span>
            @Html.HiddenFor(m => m.ID)
        </span>
        <span>
            @Html.EditorFor(m => m.AttendedDate)
            @Html.ValidationMessageFor(m=>m.AttendedDate)
        </span>
        <span>
            <button value="DeleteMeeting" name="DeleteMeeting" id="@Model.ID" class="btn btn-danger btn-sm" title="Delete meeting">
                <span class="glyphicon glyphicon-minus" aria-hidden="true"></span>
            </button>
        </span>
    }
</li>

EBContactManagement/Views/HouseHolds/_Contact.cshtml
@model EBContactManagement.Models.ContactMade


<tr>
    @using (Html.BeginCollectionItem("ContactMades"))
    {
        <td>
            @Html.HiddenFor(m => m.ID)
            @Html.HiddenFor(m => m.HouseholdID)
            @Html.DropDownListFor(m => m.ContactTypeID, (IEnumerable<SelectListItem>) ViewBag.ContactTypes,"<Select one>")
        </td>
        <td>
            @Html.EditorFor(m => m.ContactDate)
        </td>
        <td>
            @Html.DropDownListFor(m => m.ContactedByID, (IEnumerable<SelectListItem>) ViewBag.Contacter,"<Select one>")
        </td>
        <td>
            @Html.TextAreaFor(m => m.Notes, new {@class="input-large"})
        </td>
        <td>
            <button value="DeleteContact" name="DeleteContact" id="@Model.ID" class="btn btn-danger btn-sm" title="Delete contact">
                <span class="glyphicon glyphicon-minus" aria-hidden="true"></span>
            </button>
        </td>
    }
</tr>